version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Building and testing the container.
          command: make test
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}
              docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest
            fi
